apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deploy
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels: { app: be }
  template:
    metadata:
      labels: { app: be }
    spec:
      containers:
        - name: be
          image: amdp-registry.skala-ai.com/skala25a/be-deploy:d2aa97f129bc
          env:
            - name: UVICORN_WORKERS
              value: "1"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: OPENAI_API_KEY
          ports:
            - containerPort: 8000
