apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk018
  namespace: skala-practice
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: public-nginx
  rules:
    - host: sk018-ingress.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific # NGINX 정규식 매칭 허용
            backend:
              service:
                name: be-svc
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fe-svc
                port:
                  number: 80
  tls:
    - hosts:
        - sk018-ingress.skala25a.project.skala-ai.com
      secretName: sk018-ingress-project-tls-cert
