apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk018-vue-fastapi
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sk018
  source:
    repoURL: https://github.com/nOOne-is-hier/payshield.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
